import { createFileRoute } from "@tanstack/react-router";
import { Boxes, Eye, Sparkles } from "lucide-react";

import { Nav } from "@/components/koda/Nav";
import { SiteFooter } from "@/components/koda/SiteFooter";

export const Route = createFileRoute("/sobre")({ head: () => ({ meta: [{ title: "Sobre a Koda" }] }), component: About });

function About() {
  return <div className="min-h-screen bg-white text-[#1d1d1f]"><Nav/><main><section className="px-5 py-24 text-center sm:py-36"><p className="text-sm font-semibold text-[#0071e3]">Koda</p><h1 className="mx-auto mt-4 max-w-5xl text-6xl font-semibold tracking-[-0.06em] sm:text-8xl">Tecnologia que sabe quando ficar em segundo plano.</h1><p className="mx-auto mt-7 max-w-2xl text-xl font-medium leading-relaxed text-[#6e6e73]">A Koda cria produtos focados em tarefas reais do dia a dia — simples de configurar, fáceis de entender e próximos de quem usa.</p></section><section className="bg-[#f5f5f7] px-5 py-20 sm:py-28"><div className="mx-auto grid max-w-6xl gap-4 md:grid-cols-3">{[[Eye,"Clareza","A interface precisa mostrar o que importa antes de adicionar mais uma camada de complexidade."],[Boxes,"Produtos compreensíveis","Hardware, software, suporte e reparo devem fazer parte da mesma experiência."],[Sparkles,"Ideias com propósito","A Koda não precisa anunciar um catálogo de coisas que ainda não existem. Cada produto entra quando tiver uma função real."]].map(([Icon,title,text])=>{const I=Icon as typeof Eye;return <article key={title as string} className="rounded-[30px] bg-white p-8"><I className="h-8 w-8 text-[#0071e3]"/><h2 className="mt-14 text-3xl font-semibold tracking-[-0.04em]">{title as string}</h2><p className="mt-4 text-sm leading-relaxed text-[#6e6e73]">{text as string}</p></article>})}</div></section><section className="mx-auto max-w-5xl px-5 py-24 sm:py-32"><p className="text-sm font-semibold text-[#6e6e73]">Um ecossistema, não uma coleção de páginas</p><h2 className="mt-4 max-w-4xl text-5xl font-semibold tracking-[-0.05em] sm:text-6xl">KodaBot, KODA OS e KodaCloud foram pensados para se reconhecer.</h2><p className="mt-6 max-w-3xl text-lg leading-relaxed text-[#6e6e73]">O produto nasce no registro da fábrica, é ativado durante o primeiro setup e depois aparece automaticamente na conta do comprador. A mesma identidade continua no suporte, garantia, manuais e atualizações.</p></section></main><SiteFooter/></div>;
}
