/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as KodaosRouteImport } from './routes/kodaos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as KodaosIndexRouteImport } from './routes/kodaos.index'
import { Route as KodaosChangelogRouteImport } from './routes/kodaos.changelog'
import { Route as SuporteIndexRouteImport } from './routes/suporte.index'
import { Route as SuporteOrcamentosRouteImport } from './routes/suporte.orcamentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const KodaosRoute = KodaosRouteImport.update({
  id: '/kodaos',
  path: '/kodaos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const KodaosIndexRoute = KodaosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KodaosRoute,
} as any)
const KodaosChangelogRoute = KodaosChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => KodaosRoute,
} as any)
const SuporteIndexRoute = SuporteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteOrcamentosRoute = SuporteOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => SuporteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/kodaos': typeof KodaosRouteWithChildren
  '/suporte': typeof SuporteRouteWithChildren
  '/kodaos/changelog': typeof KodaosChangelogRoute
  '/suporte/orcamentos': typeof SuporteOrcamentosRoute
  '/kodaos/': typeof KodaosIndexRoute
  '/suporte/': typeof SuporteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/kodaos/changelog': typeof KodaosChangelogRoute
  '/suporte/orcamentos': typeof SuporteOrcamentosRoute
  '/kodaos': typeof KodaosIndexRoute
  '/suporte': typeof SuporteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comparar': typeof CompararRoute
  '/kodaos': typeof KodaosRouteWithChildren
  '/suporte': typeof SuporteRouteWithChildren
  '/kodaos/changelog': typeof KodaosChangelogRoute
  '/suporte/orcamentos': typeof SuporteOrcamentosRoute
  '/kodaos/': typeof KodaosIndexRoute
  '/suporte/': typeof SuporteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comparar'
    | '/kodaos'
    | '/suporte'
    | '/kodaos/changelog'
    | '/suporte/orcamentos'
    | '/kodaos/'
    | '/suporte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comparar'
    | '/kodaos/changelog'
    | '/suporte/orcamentos'
    | '/kodaos'
    | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/comparar'
    | '/kodaos'
    | '/suporte'
    | '/kodaos/changelog'
    | '/suporte/orcamentos'
    | '/kodaos/'
    | '/suporte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompararRoute: typeof CompararRoute
  KodaosRoute: typeof KodaosRouteWithChildren
  SuporteRoute: typeof SuporteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodaos': {
      id: '/kodaos'
      path: '/kodaos'
      fullPath: '/kodaos'
      preLoaderRoute: typeof KodaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodaos/': {
      id: '/kodaos/'
      path: '/'
      fullPath: '/kodaos/'
      preLoaderRoute: typeof KodaosIndexRouteImport
      parentRoute: typeof KodaosRoute
    }
    '/kodaos/changelog': {
      id: '/kodaos/changelog'
      path: '/changelog'
      fullPath: '/kodaos/changelog'
      preLoaderRoute: typeof KodaosChangelogRouteImport
      parentRoute: typeof KodaosRoute
    }
    '/suporte/': {
      id: '/suporte/'
      path: '/'
      fullPath: '/suporte/'
      preLoaderRoute: typeof SuporteIndexRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/orcamentos': {
      id: '/suporte/orcamentos'
      path: '/orcamentos'
      fullPath: '/suporte/orcamentos'
      preLoaderRoute: typeof SuporteOrcamentosRouteImport
      parentRoute: typeof SuporteRoute
    }
  }
}

interface KodaosRouteChildren {
  KodaosChangelogRoute: typeof KodaosChangelogRoute
  KodaosIndexRoute: typeof KodaosIndexRoute
}

const KodaosRouteChildren: KodaosRouteChildren = {
  KodaosChangelogRoute: KodaosChangelogRoute,
  KodaosIndexRoute: KodaosIndexRoute,
}

const KodaosRouteWithChildren =
  KodaosRoute._addFileChildren(KodaosRouteChildren)

interface SuporteRouteChildren {
  SuporteOrcamentosRoute: typeof SuporteOrcamentosRoute
  SuporteIndexRoute: typeof SuporteIndexRoute
}

const SuporteRouteChildren: SuporteRouteChildren = {
  SuporteOrcamentosRoute: SuporteOrcamentosRoute,
  SuporteIndexRoute: SuporteIndexRoute,
}

const SuporteRouteWithChildren =
  SuporteRoute._addFileChildren(SuporteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompararRoute: CompararRoute,
  KodaosRoute: KodaosRouteWithChildren,
  SuporteRoute: SuporteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
