/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtivarRouteImport } from './routes/ativar'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as FabricaRouteImport } from './routes/fabrica'
import { Route as FinanceiroInternoRouteImport } from './routes/financeiro-interno'
import { Route as KodabotRouteImport } from './routes/kodabot'
import { Route as KodabotProRouteImport } from './routes/kodabot-pro'
import { Route as KodacareRouteImport } from './routes/kodacare'
import { Route as KodaosRouteImport } from './routes/kodaos'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as SuporteInternoRouteImport } from './routes/suporte-interno'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFabricaRouteImport } from './routes/admin.fabrica'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as CheckoutProductSlugRouteImport } from './routes/checkout.$productSlug'
import { Route as ContaIndexRouteImport } from './routes/conta.index'
import { Route as ContaConfiguracoesRouteImport } from './routes/conta.configuracoes'
import { Route as ContaCriarRouteImport } from './routes/conta.criar'
import { Route as ContaEntrarRouteImport } from './routes/conta.entrar'
import { Route as ContaNotificacoesRouteImport } from './routes/conta.notificacoes'
import { Route as ContaPedidosRouteImport } from './routes/conta.pedidos'
import { Route as ContaRecuperarRouteImport } from './routes/conta.recuperar'
import { Route as ContaRedefinirRouteImport } from './routes/conta.redefinir'
import { Route as ContaReparosRouteImport } from './routes/conta.reparos'
import { Route as KodabotIComprarRouteImport } from './routes/kodabot-i.comprar'
import { Route as KodabotProIndexRouteImport } from './routes/kodabot-pro.index'
import { Route as KodabotProTechSpecsRouteImport } from './routes/kodabot-pro.tech-specs'
import { Route as KodabotIndexRouteImport } from './routes/kodabot.index'
import { Route as KodabotPorDentroRouteImport } from './routes/kodabot.por-dentro'
import { Route as KodabotTechSpecsRouteImport } from './routes/kodabot.tech-specs'
import { Route as KodaosIndexRouteImport } from './routes/kodaos.index'
import { Route as KodaosChangelogRouteImport } from './routes/kodaos.changelog'
import { Route as KodaosUpdatesRouteImport } from './routes/kodaos.updates'
import { Route as ReparosSolicitarRouteImport } from './routes/reparos.solicitar'
import { Route as SuporteIndexRouteImport } from './routes/suporte.index'
import { Route as SuporteConfigurarRouteImport } from './routes/suporte.configurar'
import { Route as SuporteContatoRouteImport } from './routes/suporte.contato'
import { Route as SuporteFaqRouteImport } from './routes/suporte.faq'
import { Route as SuporteGarantiaRouteImport } from './routes/suporte.garantia'
import { Route as SuporteManuaisRouteImport } from './routes/suporte.manuais'
import { Route as SuporteOrcamentosRouteImport } from './routes/suporte.orcamentos'
import { Route as SuporteReparoRouteImport } from './routes/suporte.reparo'
import { Route as CheckoutReparoRepairIdRouteImport } from './routes/checkout.reparo.$repairId'
import { Route as ContaCoberturaDeviceIdRouteImport } from './routes/conta.cobertura.$deviceId'
import { Route as ContaDiagnosticoDeviceIdRouteImport } from './routes/conta.diagnostico.$deviceId'
import { Route as ContaDispositivoDeviceIdRouteImport } from './routes/conta.dispositivo.$deviceId'
import { Route as ContaPedidosOrderIdRouteImport } from './routes/conta.pedidos.$orderId'
import { Route as ContaReparosRepairIdRouteImport } from './routes/conta.reparos.$repairId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarRoute = AtivarRouteImport.update({
  id: '/ativar',
  path: '/ativar',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricaRoute = FabricaRouteImport.update({
  id: '/fabrica',
  path: '/fabrica',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroInternoRoute = FinanceiroInternoRouteImport.update({
  id: '/financeiro-interno',
  path: '/financeiro-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const KodabotRoute = KodabotRouteImport.update({
  id: '/kodabot',
  path: '/kodabot',
  getParentRoute: () => rootRouteImport,
} as any)
const KodabotProRoute = KodabotProRouteImport.update({
  id: '/kodabot-pro',
  path: '/kodabot-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const KodacareRoute = KodacareRouteImport.update({
  id: '/kodacare',
  path: '/kodacare',
  getParentRoute: () => rootRouteImport,
} as any)
const KodaosRoute = KodaosRouteImport.update({
  id: '/kodaos',
  path: '/kodaos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteInternoRoute = SuporteInternoRouteImport.update({
  id: '/suporte-interno',
  path: '/suporte-interno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFabricaRoute = AdminFabricaRouteImport.update({
  id: '/fabrica',
  path: '/fabrica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutProductSlugRoute = CheckoutProductSlugRouteImport.update({
  id: '/checkout/$productSlug',
  path: '/checkout/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaRoute,
} as any)
const ContaConfiguracoesRoute = ContaConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ContaRoute,
} as any)
const ContaCriarRoute = ContaCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => ContaRoute,
} as any)
const ContaEntrarRoute = ContaEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => ContaRoute,
} as any)
const ContaNotificacoesRoute = ContaNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => ContaRoute,
} as any)
const ContaPedidosRoute = ContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaRecuperarRoute = ContaRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => ContaRoute,
} as any)
const ContaRedefinirRoute = ContaRedefinirRouteImport.update({
  id: '/redefinir',
  path: '/redefinir',
  getParentRoute: () => ContaRoute,
} as any)
const ContaReparosRoute = ContaReparosRouteImport.update({
  id: '/reparos',
  path: '/reparos',
  getParentRoute: () => ContaRoute,
} as any)
const KodabotIComprarRoute = KodabotIComprarRouteImport.update({
  id: '/kodabot-i/comprar',
  path: '/kodabot-i/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const KodabotProIndexRoute = KodabotProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KodabotProRoute,
} as any)
const KodabotProTechSpecsRoute = KodabotProTechSpecsRouteImport.update({
  id: '/tech-specs',
  path: '/tech-specs',
  getParentRoute: () => KodabotProRoute,
} as any)
const KodabotIndexRoute = KodabotIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KodabotRoute,
} as any)
const KodabotPorDentroRoute = KodabotPorDentroRouteImport.update({
  id: '/por-dentro',
  path: '/por-dentro',
  getParentRoute: () => KodabotRoute,
} as any)
const KodabotTechSpecsRoute = KodabotTechSpecsRouteImport.update({
  id: '/tech-specs',
  path: '/tech-specs',
  getParentRoute: () => KodabotRoute,
} as any)
const KodaosIndexRoute = KodaosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KodaosRoute,
} as any)
const KodaosChangelogRoute = KodaosChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => KodaosRoute,
} as any)
const KodaosUpdatesRoute = KodaosUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => KodaosRoute,
} as any)
const ReparosSolicitarRoute = ReparosSolicitarRouteImport.update({
  id: '/reparos/solicitar',
  path: '/reparos/solicitar',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteIndexRoute = SuporteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteConfigurarRoute = SuporteConfigurarRouteImport.update({
  id: '/configurar',
  path: '/configurar',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteContatoRoute = SuporteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteFaqRoute = SuporteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteGarantiaRoute = SuporteGarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteManuaisRoute = SuporteManuaisRouteImport.update({
  id: '/manuais',
  path: '/manuais',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteOrcamentosRoute = SuporteOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => SuporteRoute,
} as any)
const SuporteReparoRoute = SuporteReparoRouteImport.update({
  id: '/reparo',
  path: '/reparo',
  getParentRoute: () => SuporteRoute,
} as any)
const CheckoutReparoRepairIdRoute = CheckoutReparoRepairIdRouteImport.update({
  id: '/checkout/reparo/$repairId',
  path: '/checkout/reparo/$repairId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaCoberturaDeviceIdRoute = ContaCoberturaDeviceIdRouteImport.update({
  id: '/cobertura/$deviceId',
  path: '/cobertura/$deviceId',
  getParentRoute: () => ContaRoute,
} as any)
const ContaDiagnosticoDeviceIdRoute =
  ContaDiagnosticoDeviceIdRouteImport.update({
    id: '/diagnostico/$deviceId',
    path: '/diagnostico/$deviceId',
    getParentRoute: () => ContaRoute,
  } as any)
const ContaDispositivoDeviceIdRoute =
  ContaDispositivoDeviceIdRouteImport.update({
    id: '/dispositivo/$deviceId',
    path: '/dispositivo/$deviceId',
    getParentRoute: () => ContaRoute,
  } as any)
const ContaPedidosOrderIdRoute = ContaPedidosOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ContaPedidosRoute,
} as any)
const ContaReparosRepairIdRoute = ContaReparosRepairIdRouteImport.update({
  id: '/$repairId',
  path: '/$repairId',
  getParentRoute: () => ContaReparosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/comparar': typeof CompararRoute
  '/conta': typeof ContaRouteWithChildren
  '/contratos': typeof ContratosRoute
  '/fabrica': typeof FabricaRoute
  '/financeiro-interno': typeof FinanceiroInternoRoute
  '/kodabot': typeof KodabotRouteWithChildren
  '/kodabot-pro': typeof KodabotProRouteWithChildren
  '/kodacare': typeof KodacareRoute
  '/kodaos': typeof KodaosRouteWithChildren
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/suporte': typeof SuporteRouteWithChildren
  '/suporte-interno': typeof SuporteInternoRoute
  '/admin/fabrica': typeof AdminFabricaRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/checkout/$productSlug': typeof CheckoutProductSlugRoute
  '/conta/configuracoes': typeof ContaConfiguracoesRoute
  '/conta/criar': typeof ContaCriarRoute
  '/conta/entrar': typeof ContaEntrarRoute
  '/conta/notificacoes': typeof ContaNotificacoesRoute
  '/conta/pedidos': typeof ContaPedidosRouteWithChildren
  '/conta/recuperar': typeof ContaRecuperarRoute
  '/conta/redefinir': typeof ContaRedefinirRoute
  '/conta/reparos': typeof ContaReparosRouteWithChildren
  '/kodabot-i/comprar': typeof KodabotIComprarRoute
  '/kodabot-pro/tech-specs': typeof KodabotProTechSpecsRoute
  '/kodabot/por-dentro': typeof KodabotPorDentroRoute
  '/kodabot/tech-specs': typeof KodabotTechSpecsRoute
  '/kodaos/changelog': typeof KodaosChangelogRoute
  '/kodaos/updates': typeof KodaosUpdatesRoute
  '/reparos/solicitar': typeof ReparosSolicitarRoute
  '/suporte/configurar': typeof SuporteConfigurarRoute
  '/suporte/contato': typeof SuporteContatoRoute
  '/suporte/faq': typeof SuporteFaqRoute
  '/suporte/garantia': typeof SuporteGarantiaRoute
  '/suporte/manuais': typeof SuporteManuaisRoute
  '/suporte/orcamentos': typeof SuporteOrcamentosRoute
  '/suporte/reparo': typeof SuporteReparoRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/kodabot-pro/': typeof KodabotProIndexRoute
  '/kodabot/': typeof KodabotIndexRoute
  '/kodaos/': typeof KodaosIndexRoute
  '/suporte/': typeof SuporteIndexRoute
  '/checkout/reparo/$repairId': typeof CheckoutReparoRepairIdRoute
  '/conta/cobertura/$deviceId': typeof ContaCoberturaDeviceIdRoute
  '/conta/diagnostico/$deviceId': typeof ContaDiagnosticoDeviceIdRoute
  '/conta/dispositivo/$deviceId': typeof ContaDispositivoDeviceIdRoute
  '/conta/pedidos/$orderId': typeof ContaPedidosOrderIdRoute
  '/conta/reparos/$repairId': typeof ContaReparosRepairIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar': typeof AtivarRoute
  '/comparar': typeof CompararRoute
  '/contratos': typeof ContratosRoute
  '/fabrica': typeof FabricaRoute
  '/financeiro-interno': typeof FinanceiroInternoRoute
  '/kodacare': typeof KodacareRoute
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/suporte-interno': typeof SuporteInternoRoute
  '/admin/fabrica': typeof AdminFabricaRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/checkout/$productSlug': typeof CheckoutProductSlugRoute
  '/conta/configuracoes': typeof ContaConfiguracoesRoute
  '/conta/criar': typeof ContaCriarRoute
  '/conta/entrar': typeof ContaEntrarRoute
  '/conta/notificacoes': typeof ContaNotificacoesRoute
  '/conta/pedidos': typeof ContaPedidosRouteWithChildren
  '/conta/recuperar': typeof ContaRecuperarRoute
  '/conta/redefinir': typeof ContaRedefinirRoute
  '/conta/reparos': typeof ContaReparosRouteWithChildren
  '/kodabot-i/comprar': typeof KodabotIComprarRoute
  '/kodabot-pro/tech-specs': typeof KodabotProTechSpecsRoute
  '/kodabot/por-dentro': typeof KodabotPorDentroRoute
  '/kodabot/tech-specs': typeof KodabotTechSpecsRoute
  '/kodaos/changelog': typeof KodaosChangelogRoute
  '/kodaos/updates': typeof KodaosUpdatesRoute
  '/reparos/solicitar': typeof ReparosSolicitarRoute
  '/suporte/configurar': typeof SuporteConfigurarRoute
  '/suporte/contato': typeof SuporteContatoRoute
  '/suporte/faq': typeof SuporteFaqRoute
  '/suporte/garantia': typeof SuporteGarantiaRoute
  '/suporte/manuais': typeof SuporteManuaisRoute
  '/suporte/orcamentos': typeof SuporteOrcamentosRoute
  '/suporte/reparo': typeof SuporteReparoRoute
  '/admin': typeof AdminIndexRoute
  '/conta': typeof ContaIndexRoute
  '/kodabot-pro': typeof KodabotProIndexRoute
  '/kodabot': typeof KodabotIndexRoute
  '/kodaos': typeof KodaosIndexRoute
  '/suporte': typeof SuporteIndexRoute
  '/checkout/reparo/$repairId': typeof CheckoutReparoRepairIdRoute
  '/conta/cobertura/$deviceId': typeof ContaCoberturaDeviceIdRoute
  '/conta/diagnostico/$deviceId': typeof ContaDiagnosticoDeviceIdRoute
  '/conta/dispositivo/$deviceId': typeof ContaDispositivoDeviceIdRoute
  '/conta/pedidos/$orderId': typeof ContaPedidosOrderIdRoute
  '/conta/reparos/$repairId': typeof ContaReparosRepairIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/comparar': typeof CompararRoute
  '/conta': typeof ContaRouteWithChildren
  '/contratos': typeof ContratosRoute
  '/fabrica': typeof FabricaRoute
  '/financeiro-interno': typeof FinanceiroInternoRoute
  '/kodabot': typeof KodabotRouteWithChildren
  '/kodabot-pro': typeof KodabotProRouteWithChildren
  '/kodacare': typeof KodacareRoute
  '/kodaos': typeof KodaosRouteWithChildren
  '/loja': typeof LojaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/suporte': typeof SuporteRouteWithChildren
  '/suporte-interno': typeof SuporteInternoRoute
  '/admin/fabrica': typeof AdminFabricaRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/checkout/$productSlug': typeof CheckoutProductSlugRoute
  '/conta/configuracoes': typeof ContaConfiguracoesRoute
  '/conta/criar': typeof ContaCriarRoute
  '/conta/entrar': typeof ContaEntrarRoute
  '/conta/notificacoes': typeof ContaNotificacoesRoute
  '/conta/pedidos': typeof ContaPedidosRouteWithChildren
  '/conta/recuperar': typeof ContaRecuperarRoute
  '/conta/redefinir': typeof ContaRedefinirRoute
  '/conta/reparos': typeof ContaReparosRouteWithChildren
  '/kodabot-i/comprar': typeof KodabotIComprarRoute
  '/kodabot-pro/tech-specs': typeof KodabotProTechSpecsRoute
  '/kodabot/por-dentro': typeof KodabotPorDentroRoute
  '/kodabot/tech-specs': typeof KodabotTechSpecsRoute
  '/kodaos/changelog': typeof KodaosChangelogRoute
  '/kodaos/updates': typeof KodaosUpdatesRoute
  '/reparos/solicitar': typeof ReparosSolicitarRoute
  '/suporte/configurar': typeof SuporteConfigurarRoute
  '/suporte/contato': typeof SuporteContatoRoute
  '/suporte/faq': typeof SuporteFaqRoute
  '/suporte/garantia': typeof SuporteGarantiaRoute
  '/suporte/manuais': typeof SuporteManuaisRoute
  '/suporte/orcamentos': typeof SuporteOrcamentosRoute
  '/suporte/reparo': typeof SuporteReparoRoute
  '/admin/': typeof AdminIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/kodabot-pro/': typeof KodabotProIndexRoute
  '/kodabot/': typeof KodabotIndexRoute
  '/kodaos/': typeof KodaosIndexRoute
  '/suporte/': typeof SuporteIndexRoute
  '/checkout/reparo/$repairId': typeof CheckoutReparoRepairIdRoute
  '/conta/cobertura/$deviceId': typeof ContaCoberturaDeviceIdRoute
  '/conta/diagnostico/$deviceId': typeof ContaDiagnosticoDeviceIdRoute
  '/conta/dispositivo/$deviceId': typeof ContaDispositivoDeviceIdRoute
  '/conta/pedidos/$orderId': typeof ContaPedidosOrderIdRoute
  '/conta/reparos/$repairId': typeof ContaReparosRepairIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ativar'
    | '/comparar'
    | '/conta'
    | '/contratos'
    | '/fabrica'
    | '/financeiro-interno'
    | '/kodabot'
    | '/kodabot-pro'
    | '/kodacare'
    | '/kodaos'
    | '/loja'
    | '/privacidade'
    | '/sobre'
    | '/status'
    | '/suporte'
    | '/suporte-interno'
    | '/admin/fabrica'
    | '/admin/financeiro'
    | '/admin/suporte'
    | '/checkout/$productSlug'
    | '/conta/configuracoes'
    | '/conta/criar'
    | '/conta/entrar'
    | '/conta/notificacoes'
    | '/conta/pedidos'
    | '/conta/recuperar'
    | '/conta/redefinir'
    | '/conta/reparos'
    | '/kodabot-i/comprar'
    | '/kodabot-pro/tech-specs'
    | '/kodabot/por-dentro'
    | '/kodabot/tech-specs'
    | '/kodaos/changelog'
    | '/kodaos/updates'
    | '/reparos/solicitar'
    | '/suporte/configurar'
    | '/suporte/contato'
    | '/suporte/faq'
    | '/suporte/garantia'
    | '/suporte/manuais'
    | '/suporte/orcamentos'
    | '/suporte/reparo'
    | '/admin/'
    | '/conta/'
    | '/kodabot-pro/'
    | '/kodabot/'
    | '/kodaos/'
    | '/suporte/'
    | '/checkout/reparo/$repairId'
    | '/conta/cobertura/$deviceId'
    | '/conta/diagnostico/$deviceId'
    | '/conta/dispositivo/$deviceId'
    | '/conta/pedidos/$orderId'
    | '/conta/reparos/$repairId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar'
    | '/comparar'
    | '/contratos'
    | '/fabrica'
    | '/financeiro-interno'
    | '/kodacare'
    | '/loja'
    | '/privacidade'
    | '/sobre'
    | '/status'
    | '/suporte-interno'
    | '/admin/fabrica'
    | '/admin/financeiro'
    | '/admin/suporte'
    | '/checkout/$productSlug'
    | '/conta/configuracoes'
    | '/conta/criar'
    | '/conta/entrar'
    | '/conta/notificacoes'
    | '/conta/pedidos'
    | '/conta/recuperar'
    | '/conta/redefinir'
    | '/conta/reparos'
    | '/kodabot-i/comprar'
    | '/kodabot-pro/tech-specs'
    | '/kodabot/por-dentro'
    | '/kodabot/tech-specs'
    | '/kodaos/changelog'
    | '/kodaos/updates'
    | '/reparos/solicitar'
    | '/suporte/configurar'
    | '/suporte/contato'
    | '/suporte/faq'
    | '/suporte/garantia'
    | '/suporte/manuais'
    | '/suporte/orcamentos'
    | '/suporte/reparo'
    | '/admin'
    | '/conta'
    | '/kodabot-pro'
    | '/kodabot'
    | '/kodaos'
    | '/suporte'
    | '/checkout/reparo/$repairId'
    | '/conta/cobertura/$deviceId'
    | '/conta/diagnostico/$deviceId'
    | '/conta/dispositivo/$deviceId'
    | '/conta/pedidos/$orderId'
    | '/conta/reparos/$repairId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ativar'
    | '/comparar'
    | '/conta'
    | '/contratos'
    | '/fabrica'
    | '/financeiro-interno'
    | '/kodabot'
    | '/kodabot-pro'
    | '/kodacare'
    | '/kodaos'
    | '/loja'
    | '/privacidade'
    | '/sobre'
    | '/status'
    | '/suporte'
    | '/suporte-interno'
    | '/admin/fabrica'
    | '/admin/financeiro'
    | '/admin/suporte'
    | '/checkout/$productSlug'
    | '/conta/configuracoes'
    | '/conta/criar'
    | '/conta/entrar'
    | '/conta/notificacoes'
    | '/conta/pedidos'
    | '/conta/recuperar'
    | '/conta/redefinir'
    | '/conta/reparos'
    | '/kodabot-i/comprar'
    | '/kodabot-pro/tech-specs'
    | '/kodabot/por-dentro'
    | '/kodabot/tech-specs'
    | '/kodaos/changelog'
    | '/kodaos/updates'
    | '/reparos/solicitar'
    | '/suporte/configurar'
    | '/suporte/contato'
    | '/suporte/faq'
    | '/suporte/garantia'
    | '/suporte/manuais'
    | '/suporte/orcamentos'
    | '/suporte/reparo'
    | '/admin/'
    | '/conta/'
    | '/kodabot-pro/'
    | '/kodabot/'
    | '/kodaos/'
    | '/suporte/'
    | '/checkout/reparo/$repairId'
    | '/conta/cobertura/$deviceId'
    | '/conta/diagnostico/$deviceId'
    | '/conta/dispositivo/$deviceId'
    | '/conta/pedidos/$orderId'
    | '/conta/reparos/$repairId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtivarRoute: typeof AtivarRoute
  CompararRoute: typeof CompararRoute
  ContaRoute: typeof ContaRouteWithChildren
  ContratosRoute: typeof ContratosRoute
  FabricaRoute: typeof FabricaRoute
  FinanceiroInternoRoute: typeof FinanceiroInternoRoute
  KodabotRoute: typeof KodabotRouteWithChildren
  KodabotProRoute: typeof KodabotProRouteWithChildren
  KodacareRoute: typeof KodacareRoute
  KodaosRoute: typeof KodaosRouteWithChildren
  LojaRoute: typeof LojaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  StatusRoute: typeof StatusRoute
  SuporteRoute: typeof SuporteRouteWithChildren
  SuporteInternoRoute: typeof SuporteInternoRoute
  CheckoutProductSlugRoute: typeof CheckoutProductSlugRoute
  KodabotIComprarRoute: typeof KodabotIComprarRoute
  ReparosSolicitarRoute: typeof ReparosSolicitarRoute
  CheckoutReparoRepairIdRoute: typeof CheckoutReparoRepairIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar': {
      id: '/ativar'
      path: '/ativar'
      fullPath: '/ativar'
      preLoaderRoute: typeof AtivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrica': {
      id: '/fabrica'
      path: '/fabrica'
      fullPath: '/fabrica'
      preLoaderRoute: typeof FabricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro-interno': {
      id: '/financeiro-interno'
      path: '/financeiro-interno'
      fullPath: '/financeiro-interno'
      preLoaderRoute: typeof FinanceiroInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodabot': {
      id: '/kodabot'
      path: '/kodabot'
      fullPath: '/kodabot'
      preLoaderRoute: typeof KodabotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodabot-pro': {
      id: '/kodabot-pro'
      path: '/kodabot-pro'
      fullPath: '/kodabot-pro'
      preLoaderRoute: typeof KodabotProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodacare': {
      id: '/kodacare'
      path: '/kodacare'
      fullPath: '/kodacare'
      preLoaderRoute: typeof KodacareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodaos': {
      id: '/kodaos'
      path: '/kodaos'
      fullPath: '/kodaos'
      preLoaderRoute: typeof KodaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte-interno': {
      id: '/suporte-interno'
      path: '/suporte-interno'
      fullPath: '/suporte-interno'
      preLoaderRoute: typeof SuporteInternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fabrica': {
      id: '/admin/fabrica'
      path: '/fabrica'
      fullPath: '/admin/fabrica'
      preLoaderRoute: typeof AdminFabricaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/$productSlug': {
      id: '/checkout/$productSlug'
      path: '/checkout/$productSlug'
      fullPath: '/checkout/$productSlug'
      preLoaderRoute: typeof CheckoutProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/': {
      id: '/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/configuracoes': {
      id: '/conta/configuracoes'
      path: '/configuracoes'
      fullPath: '/conta/configuracoes'
      preLoaderRoute: typeof ContaConfiguracoesRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/criar': {
      id: '/conta/criar'
      path: '/criar'
      fullPath: '/conta/criar'
      preLoaderRoute: typeof ContaCriarRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/entrar': {
      id: '/conta/entrar'
      path: '/entrar'
      fullPath: '/conta/entrar'
      preLoaderRoute: typeof ContaEntrarRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/notificacoes': {
      id: '/conta/notificacoes'
      path: '/notificacoes'
      fullPath: '/conta/notificacoes'
      preLoaderRoute: typeof ContaNotificacoesRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/pedidos': {
      id: '/conta/pedidos'
      path: '/pedidos'
      fullPath: '/conta/pedidos'
      preLoaderRoute: typeof ContaPedidosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/recuperar': {
      id: '/conta/recuperar'
      path: '/recuperar'
      fullPath: '/conta/recuperar'
      preLoaderRoute: typeof ContaRecuperarRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/redefinir': {
      id: '/conta/redefinir'
      path: '/redefinir'
      fullPath: '/conta/redefinir'
      preLoaderRoute: typeof ContaRedefinirRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/reparos': {
      id: '/conta/reparos'
      path: '/reparos'
      fullPath: '/conta/reparos'
      preLoaderRoute: typeof ContaReparosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/kodabot-i/comprar': {
      id: '/kodabot-i/comprar'
      path: '/kodabot-i/comprar'
      fullPath: '/kodabot-i/comprar'
      preLoaderRoute: typeof KodabotIComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kodabot-pro/': {
      id: '/kodabot-pro/'
      path: '/'
      fullPath: '/kodabot-pro/'
      preLoaderRoute: typeof KodabotProIndexRouteImport
      parentRoute: typeof KodabotProRoute
    }
    '/kodabot-pro/tech-specs': {
      id: '/kodabot-pro/tech-specs'
      path: '/tech-specs'
      fullPath: '/kodabot-pro/tech-specs'
      preLoaderRoute: typeof KodabotProTechSpecsRouteImport
      parentRoute: typeof KodabotProRoute
    }
    '/kodabot/': {
      id: '/kodabot/'
      path: '/'
      fullPath: '/kodabot/'
      preLoaderRoute: typeof KodabotIndexRouteImport
      parentRoute: typeof KodabotRoute
    }
    '/kodabot/por-dentro': {
      id: '/kodabot/por-dentro'
      path: '/por-dentro'
      fullPath: '/kodabot/por-dentro'
      preLoaderRoute: typeof KodabotPorDentroRouteImport
      parentRoute: typeof KodabotRoute
    }
    '/kodabot/tech-specs': {
      id: '/kodabot/tech-specs'
      path: '/tech-specs'
      fullPath: '/kodabot/tech-specs'
      preLoaderRoute: typeof KodabotTechSpecsRouteImport
      parentRoute: typeof KodabotRoute
    }
    '/kodaos/': {
      id: '/kodaos/'
      path: '/'
      fullPath: '/kodaos/'
      preLoaderRoute: typeof KodaosIndexRouteImport
      parentRoute: typeof KodaosRoute
    }
    '/kodaos/changelog': {
      id: '/kodaos/changelog'
      path: '/changelog'
      fullPath: '/kodaos/changelog'
      preLoaderRoute: typeof KodaosChangelogRouteImport
      parentRoute: typeof KodaosRoute
    }
    '/kodaos/updates': {
      id: '/kodaos/updates'
      path: '/updates'
      fullPath: '/kodaos/updates'
      preLoaderRoute: typeof KodaosUpdatesRouteImport
      parentRoute: typeof KodaosRoute
    }
    '/reparos/solicitar': {
      id: '/reparos/solicitar'
      path: '/reparos/solicitar'
      fullPath: '/reparos/solicitar'
      preLoaderRoute: typeof ReparosSolicitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte/': {
      id: '/suporte/'
      path: '/'
      fullPath: '/suporte/'
      preLoaderRoute: typeof SuporteIndexRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/configurar': {
      id: '/suporte/configurar'
      path: '/configurar'
      fullPath: '/suporte/configurar'
      preLoaderRoute: typeof SuporteConfigurarRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/contato': {
      id: '/suporte/contato'
      path: '/contato'
      fullPath: '/suporte/contato'
      preLoaderRoute: typeof SuporteContatoRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/faq': {
      id: '/suporte/faq'
      path: '/faq'
      fullPath: '/suporte/faq'
      preLoaderRoute: typeof SuporteFaqRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/garantia': {
      id: '/suporte/garantia'
      path: '/garantia'
      fullPath: '/suporte/garantia'
      preLoaderRoute: typeof SuporteGarantiaRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/manuais': {
      id: '/suporte/manuais'
      path: '/manuais'
      fullPath: '/suporte/manuais'
      preLoaderRoute: typeof SuporteManuaisRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/orcamentos': {
      id: '/suporte/orcamentos'
      path: '/orcamentos'
      fullPath: '/suporte/orcamentos'
      preLoaderRoute: typeof SuporteOrcamentosRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/suporte/reparo': {
      id: '/suporte/reparo'
      path: '/reparo'
      fullPath: '/suporte/reparo'
      preLoaderRoute: typeof SuporteReparoRouteImport
      parentRoute: typeof SuporteRoute
    }
    '/checkout/reparo/$repairId': {
      id: '/checkout/reparo/$repairId'
      path: '/checkout/reparo/$repairId'
      fullPath: '/checkout/reparo/$repairId'
      preLoaderRoute: typeof CheckoutReparoRepairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/cobertura/$deviceId': {
      id: '/conta/cobertura/$deviceId'
      path: '/cobertura/$deviceId'
      fullPath: '/conta/cobertura/$deviceId'
      preLoaderRoute: typeof ContaCoberturaDeviceIdRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/diagnostico/$deviceId': {
      id: '/conta/diagnostico/$deviceId'
      path: '/diagnostico/$deviceId'
      fullPath: '/conta/diagnostico/$deviceId'
      preLoaderRoute: typeof ContaDiagnosticoDeviceIdRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/dispositivo/$deviceId': {
      id: '/conta/dispositivo/$deviceId'
      path: '/dispositivo/$deviceId'
      fullPath: '/conta/dispositivo/$deviceId'
      preLoaderRoute: typeof ContaDispositivoDeviceIdRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/pedidos/$orderId': {
      id: '/conta/pedidos/$orderId'
      path: '/$orderId'
      fullPath: '/conta/pedidos/$orderId'
      preLoaderRoute: typeof ContaPedidosOrderIdRouteImport
      parentRoute: typeof ContaPedidosRoute
    }
    '/conta/reparos/$repairId': {
      id: '/conta/reparos/$repairId'
      path: '/$repairId'
      fullPath: '/conta/reparos/$repairId'
      preLoaderRoute: typeof ContaReparosRepairIdRouteImport
      parentRoute: typeof ContaReparosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFabricaRoute: typeof AdminFabricaRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFabricaRoute: AdminFabricaRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ContaPedidosRouteChildren {
  ContaPedidosOrderIdRoute: typeof ContaPedidosOrderIdRoute
}

const ContaPedidosRouteChildren: ContaPedidosRouteChildren = {
  ContaPedidosOrderIdRoute: ContaPedidosOrderIdRoute,
}

const ContaPedidosRouteWithChildren = ContaPedidosRoute._addFileChildren(
  ContaPedidosRouteChildren,
)

interface ContaReparosRouteChildren {
  ContaReparosRepairIdRoute: typeof ContaReparosRepairIdRoute
}

const ContaReparosRouteChildren: ContaReparosRouteChildren = {
  ContaReparosRepairIdRoute: ContaReparosRepairIdRoute,
}

const ContaReparosRouteWithChildren = ContaReparosRoute._addFileChildren(
  ContaReparosRouteChildren,
)

interface ContaRouteChildren {
  ContaConfiguracoesRoute: typeof ContaConfiguracoesRoute
  ContaCriarRoute: typeof ContaCriarRoute
  ContaEntrarRoute: typeof ContaEntrarRoute
  ContaNotificacoesRoute: typeof ContaNotificacoesRoute
  ContaPedidosRoute: typeof ContaPedidosRouteWithChildren
  ContaRecuperarRoute: typeof ContaRecuperarRoute
  ContaRedefinirRoute: typeof ContaRedefinirRoute
  ContaReparosRoute: typeof ContaReparosRouteWithChildren
  ContaIndexRoute: typeof ContaIndexRoute
  ContaCoberturaDeviceIdRoute: typeof ContaCoberturaDeviceIdRoute
  ContaDiagnosticoDeviceIdRoute: typeof ContaDiagnosticoDeviceIdRoute
  ContaDispositivoDeviceIdRoute: typeof ContaDispositivoDeviceIdRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaConfiguracoesRoute: ContaConfiguracoesRoute,
  ContaCriarRoute: ContaCriarRoute,
  ContaEntrarRoute: ContaEntrarRoute,
  ContaNotificacoesRoute: ContaNotificacoesRoute,
  ContaPedidosRoute: ContaPedidosRouteWithChildren,
  ContaRecuperarRoute: ContaRecuperarRoute,
  ContaRedefinirRoute: ContaRedefinirRoute,
  ContaReparosRoute: ContaReparosRouteWithChildren,
  ContaIndexRoute: ContaIndexRoute,
  ContaCoberturaDeviceIdRoute: ContaCoberturaDeviceIdRoute,
  ContaDiagnosticoDeviceIdRoute: ContaDiagnosticoDeviceIdRoute,
  ContaDispositivoDeviceIdRoute: ContaDispositivoDeviceIdRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

interface KodabotRouteChildren {
  KodabotPorDentroRoute: typeof KodabotPorDentroRoute
  KodabotTechSpecsRoute: typeof KodabotTechSpecsRoute
  KodabotIndexRoute: typeof KodabotIndexRoute
}

const KodabotRouteChildren: KodabotRouteChildren = {
  KodabotPorDentroRoute: KodabotPorDentroRoute,
  KodabotTechSpecsRoute: KodabotTechSpecsRoute,
  KodabotIndexRoute: KodabotIndexRoute,
}

const KodabotRouteWithChildren =
  KodabotRoute._addFileChildren(KodabotRouteChildren)

interface KodabotProRouteChildren {
  KodabotProTechSpecsRoute: typeof KodabotProTechSpecsRoute
  KodabotProIndexRoute: typeof KodabotProIndexRoute
}

const KodabotProRouteChildren: KodabotProRouteChildren = {
  KodabotProTechSpecsRoute: KodabotProTechSpecsRoute,
  KodabotProIndexRoute: KodabotProIndexRoute,
}

const KodabotProRouteWithChildren = KodabotProRoute._addFileChildren(
  KodabotProRouteChildren,
)

interface KodaosRouteChildren {
  KodaosChangelogRoute: typeof KodaosChangelogRoute
  KodaosUpdatesRoute: typeof KodaosUpdatesRoute
  KodaosIndexRoute: typeof KodaosIndexRoute
}

const KodaosRouteChildren: KodaosRouteChildren = {
  KodaosChangelogRoute: KodaosChangelogRoute,
  KodaosUpdatesRoute: KodaosUpdatesRoute,
  KodaosIndexRoute: KodaosIndexRoute,
}

const KodaosRouteWithChildren =
  KodaosRoute._addFileChildren(KodaosRouteChildren)

interface SuporteRouteChildren {
  SuporteConfigurarRoute: typeof SuporteConfigurarRoute
  SuporteContatoRoute: typeof SuporteContatoRoute
  SuporteFaqRoute: typeof SuporteFaqRoute
  SuporteGarantiaRoute: typeof SuporteGarantiaRoute
  SuporteManuaisRoute: typeof SuporteManuaisRoute
  SuporteOrcamentosRoute: typeof SuporteOrcamentosRoute
  SuporteReparoRoute: typeof SuporteReparoRoute
  SuporteIndexRoute: typeof SuporteIndexRoute
}

const SuporteRouteChildren: SuporteRouteChildren = {
  SuporteConfigurarRoute: SuporteConfigurarRoute,
  SuporteContatoRoute: SuporteContatoRoute,
  SuporteFaqRoute: SuporteFaqRoute,
  SuporteGarantiaRoute: SuporteGarantiaRoute,
  SuporteManuaisRoute: SuporteManuaisRoute,
  SuporteOrcamentosRoute: SuporteOrcamentosRoute,
  SuporteReparoRoute: SuporteReparoRoute,
  SuporteIndexRoute: SuporteIndexRoute,
}

const SuporteRouteWithChildren =
  SuporteRoute._addFileChildren(SuporteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AtivarRoute: AtivarRoute,
  CompararRoute: CompararRoute,
  ContaRoute: ContaRouteWithChildren,
  ContratosRoute: ContratosRoute,
  FabricaRoute: FabricaRoute,
  FinanceiroInternoRoute: FinanceiroInternoRoute,
  KodabotRoute: KodabotRouteWithChildren,
  KodabotProRoute: KodabotProRouteWithChildren,
  KodacareRoute: KodacareRoute,
  KodaosRoute: KodaosRouteWithChildren,
  LojaRoute: LojaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  StatusRoute: StatusRoute,
  SuporteRoute: SuporteRouteWithChildren,
  SuporteInternoRoute: SuporteInternoRoute,
  CheckoutProductSlugRoute: CheckoutProductSlugRoute,
  KodabotIComprarRoute: KodabotIComprarRoute,
  ReparosSolicitarRoute: ReparosSolicitarRoute,
  CheckoutReparoRepairIdRoute: CheckoutReparoRepairIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
