// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_MIGRATION_KEY = 'koda:supabase-project-id';

function getSupabaseConfig() {
  const url = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const publishableKey =
    import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];
  const configuredProjectId =
    import.meta.env['VITE_SUPABASE_PROJECT_ID'] || process.env['SUPABASE_PROJECT_ID'];

  if (!url || !publishableKey) {
    const missing = [
      ...(!url ? ['VITE_SUPABASE_URL'] : []),
      ...(!publishableKey ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    throw new Error(`Missing Supabase environment variable(s): ${missing.join(', ')}`);
  }

  const projectId = new URL(url).hostname.split('.')[0];
  if (configuredProjectId && configuredProjectId !== projectId) {
    throw new Error('Supabase project ID does not match the configured Supabase URL');
  }

  return { url, publishableKey, projectId };
}

function migrateBrowserAuthStorage(projectId: string) {
  if (typeof window === 'undefined') return;

  try {
    if (localStorage.getItem(SUPABASE_MIGRATION_KEY) === projectId) return;

    // Supabase stores sessions and PKCE data under sb-<project>-auth-token keys.
    // Remove only those auth entries once when this site changes Supabase projects.
    for (let index = localStorage.length - 1; index >= 0; index -= 1) {
      const key = localStorage.key(index);
      if (key?.startsWith('sb-') && key.includes('-auth-token')) {
        localStorage.removeItem(key);
      }
    }

    localStorage.setItem(SUPABASE_MIGRATION_KEY, projectId);
  } catch {
    // Supabase will fall back to its normal behavior when browser storage is unavailable.
  }
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  const { url, publishableKey, projectId } = getSupabaseConfig();
  migrateBrowserAuthStorage(projectId);

  return createClient<Database>(url, publishableKey, {
    global: {
      fetch: createSupabaseFetch(publishableKey),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      storageKey: `sb-${projectId}-auth-token`,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
